/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    networks: Network;
    treasury: Treasury;
    transactions: Transaction;
    batches: Batch;
    'exchange-rates': ExchangeRate;
    'fiat-to-crypto': FiatToCrypto;
    'crypto-to-fiat': CryptoToFiat;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    batches: {
      transactions: 'transactions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    networks: NetworksSelect<false> | NetworksSelect<true>;
    treasury: TreasurySelect<false> | TreasurySelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    batches: BatchesSelect<false> | BatchesSelect<true>;
    'exchange-rates': ExchangeRatesSelect<false> | ExchangeRatesSelect<true>;
    'fiat-to-crypto': FiatToCryptoSelect<false> | FiatToCryptoSelect<true>;
    'crypto-to-fiat': CryptoToFiatSelect<false> | CryptoToFiatSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networks".
 */
export interface Network {
  id: number;
  /**
   * e.g. Ethereum, BEP20, Tron, Polygon
   */
  name: string;
  /**
   * e.g. eth, bep20, trx, polygon
   */
  symbol: string;
  networkType: 'mainnet' | 'testnet';
  /**
   * JSON-RPC endpoint for this network (e.g. https://bsc-dataseed.binance.org)
   */
  rpcUrl: string;
  /**
   * USDT token contract address on this network
   */
  usdtContractAddress: string;
  /**
   * Number of decimals for USDT on this network (e.g. 6 for Ethereum/Tron, 18 for BSC)
   */
  usdtDecimals: number;
  /**
   * e.g. ETH, BNB, TRX, MATIC
   */
  gasFeeTokenName: string;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treasury".
 */
export interface Treasury {
  id: number;
  /**
   * A friendly name to identify this wallet (e.g. 'Main USDT Wallet')
   */
  walletName: string;
  /**
   * Public address of your system wallet
   */
  walletAddress: string;
  /**
   * Encrypted at rest. Enter the raw private key — it will be encrypted on save.
   */
  privateKey?: string | null;
  network: number | Network;
  /**
   * Track available funds
   */
  currentBalance?: number | null;
  /**
   * Latest transaction from this wallet
   */
  latestTransactionAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * Auto-generated Order ID
   */
  orderId?: string | null;
  /**
   * Direction of the exchange
   */
  type: 'fiat_to_crypto' | 'crypto_to_fiat';
  status:
    | 'pending'
    | 'confirmed'
    | 'fiat_received'
    | 'crypto_received'
    | 'processing'
    | 'completed'
    | 'refunded'
    | 'review_needed';
  /**
   * Source treasury wallet for the transfer
   */
  treasury: number | Treasury;
  network: number | Network;
  /**
   * Amount in source currency (PHP for fiat→crypto, USDT for crypto→fiat)
   */
  amountPhp: number;
  /**
   * Destination wallet address for the transfer
   */
  targetAddress?: string | null;
  /**
   * Structured payout details (Account Name and Account Number).
   */
  bankDetails?: string | null;
  /**
   * USDT amount sent to exchange at original/reference context.
   */
  amountUsdtOriginal?: number | null;
  /**
   * Auto-computed at the markup/applied exchange rate
   */
  amountUsdt?: number | null;
  /**
   * Select the exchange rate to use for this transaction
   */
  exchangeRate: number | ExchangeRate;
  rateSnapshot?: number | null;
  referenceRateSnapshot?: number | null;
  appliedRateSnapshot?: number | null;
  usdtToPhpReferenceRateSnapshot?: number | null;
  usdtToPhpRateSnapshot?: number | null;
  phpToUsdtReferenceRateSnapshot?: number | null;
  phpToUsdtRateSnapshot?: number | null;
  /**
   * Calculated difference based on transaction type
   */
  profit?: number | null;
  /**
   * Transfer fee amount
   */
  gasFee?: number | null;
  /**
   * On-chain transaction hash after transfer
   */
  txHash?: string | null;
  /**
   * Nullable initially, assigned when batched
   */
  batch?: (number | null) | Batch;
  /**
   * Reason for failure or review flag
   */
  failReason?: string | null;
  /**
   * Optional reference to a fiat settlement
   */
  fiatSettlementId?: string | null;
  /**
   * Attached from Confirm Sending or Confirm Done actions.
   */
  invoiceImage?: (number | null) | Media;
  /**
   * Optional notes for context when this transaction is created manually in admin or through API integration.
   */
  notes?: string | null;
  receivedRecord?: (number | null) | FiatToCrypto;
  sendingRecord?: (number | null) | CryptoToFiat;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates".
 */
export interface ExchangeRate {
  id: number;
  /**
   * Fixed pair for this exchange rate configuration.
   */
  pair: string;
  usdtToPhpReferenceRate: number;
  usdtToPhpRate: number;
  usdtToPhpMarkupPercentage?: number | null;
  usdtToPhpSpread?: number | null;
  usdtToPhpSpreadPercentage?: number | null;
  phpToUsdtReferenceRate: number;
  phpToUsdtSpread?: number | null;
  phpToUsdtRate: number;
  phpToUsdtMarkupPercentage?: number | null;
  phpToUsdtSpreadPercentage?: number | null;
  isActive?: boolean | null;
  _lastEdited?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches".
 */
export interface Batch {
  id: number;
  /**
   * Total number of transactions in this batch
   */
  transactionCount: number;
  /**
   * Total gross USDT before fees
   */
  totalUsdtBatched: number;
  /**
   * Total exchange fees collected
   */
  totalFeeUsdt: number;
  /**
   * Total USDT sent to users after fees
   */
  totalNetUsdt: number;
  totalTrxSuccess?: number | null;
  totalTrxFail?: number | null;
  status: 'processing' | 'partial_success' | 'success' | 'failed';
  executedAt?: string | null;
  /**
   * Transactions included in this batch
   */
  transactions?: {
    docs?: (number | Transaction)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fiat-to-crypto".
 */
export interface FiatToCrypto {
  id: number;
  /**
   * Fiat to Crypto flow: user sends Philippine Peso (₱), then receives USDT in this record.
   */
  amount: number;
  currency: 'USDT';
  userSendsDetail?: string | null;
  amountSentToExchangeOriginalRateDetail?: string | null;
  amountReceivedFromExchangeDetail?: string | null;
  rateDetail?: string | null;
  profitAmountDetail?: string | null;
  profitPercentageDetail?: string | null;
  userReceivesDetail?: string | null;
  sentToReference?: string | null;
  transaction: number | Transaction;
  status: 'pending' | 'confirmed' | 'processing' | 'completed';
  /**
   * Required after confirming fiat send.
   */
  invoiceImage?: (number | null) | Media;
  method?: ('bank_transfer' | 'crypto') | null;
  referenceNumber?: string | null;
  senderAddress?: string | null;
  txHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crypto-to-fiat".
 */
export interface CryptoToFiat {
  id: number;
  /**
   * Crypto to Fiat flow: user sends USDT, then receives Philippine Peso (₱) in the linked transaction.
   */
  amount: number;
  currency: 'USDT';
  userSendsDetail?: string | null;
  amountSentToExchangeOriginalRateDetail?: string | null;
  amountReceivedFromExchangeDetail?: string | null;
  rateDetail?: string | null;
  profitAmountDetail?: string | null;
  profitPercentageDetail?: string | null;
  userReceivesDetail?: string | null;
  sentToReference?: string | null;
  transaction: number | Transaction;
  status: 'pending' | 'confirmed' | 'processing' | 'completed' | 'failed';
  method?: ('bank_transfer' | 'crypto') | null;
  /**
   * Optional blockchain hash once crypto send is confirmed.
   */
  txHash?: string | null;
  /**
   * Optional fiat payout destination details.
   */
  receiverDetails?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'networks';
        value: number | Network;
      } | null)
    | ({
        relationTo: 'treasury';
        value: number | Treasury;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'batches';
        value: number | Batch;
      } | null)
    | ({
        relationTo: 'exchange-rates';
        value: number | ExchangeRate;
      } | null)
    | ({
        relationTo: 'fiat-to-crypto';
        value: number | FiatToCrypto;
      } | null)
    | ({
        relationTo: 'crypto-to-fiat';
        value: number | CryptoToFiat;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networks_select".
 */
export interface NetworksSelect<T extends boolean = true> {
  name?: T;
  symbol?: T;
  networkType?: T;
  rpcUrl?: T;
  usdtContractAddress?: T;
  usdtDecimals?: T;
  gasFeeTokenName?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treasury_select".
 */
export interface TreasurySelect<T extends boolean = true> {
  walletName?: T;
  walletAddress?: T;
  privateKey?: T;
  network?: T;
  currentBalance?: T;
  latestTransactionAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  orderId?: T;
  type?: T;
  status?: T;
  treasury?: T;
  network?: T;
  amountPhp?: T;
  targetAddress?: T;
  bankDetails?: T;
  amountUsdtOriginal?: T;
  amountUsdt?: T;
  exchangeRate?: T;
  rateSnapshot?: T;
  referenceRateSnapshot?: T;
  appliedRateSnapshot?: T;
  usdtToPhpReferenceRateSnapshot?: T;
  usdtToPhpRateSnapshot?: T;
  phpToUsdtReferenceRateSnapshot?: T;
  phpToUsdtRateSnapshot?: T;
  profit?: T;
  gasFee?: T;
  txHash?: T;
  batch?: T;
  failReason?: T;
  fiatSettlementId?: T;
  invoiceImage?: T;
  notes?: T;
  receivedRecord?: T;
  sendingRecord?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches_select".
 */
export interface BatchesSelect<T extends boolean = true> {
  transactionCount?: T;
  totalUsdtBatched?: T;
  totalFeeUsdt?: T;
  totalNetUsdt?: T;
  totalTrxSuccess?: T;
  totalTrxFail?: T;
  status?: T;
  executedAt?: T;
  transactions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates_select".
 */
export interface ExchangeRatesSelect<T extends boolean = true> {
  pair?: T;
  usdtToPhpReferenceRate?: T;
  usdtToPhpRate?: T;
  usdtToPhpMarkupPercentage?: T;
  usdtToPhpSpread?: T;
  usdtToPhpSpreadPercentage?: T;
  phpToUsdtReferenceRate?: T;
  phpToUsdtSpread?: T;
  phpToUsdtRate?: T;
  phpToUsdtMarkupPercentage?: T;
  phpToUsdtSpreadPercentage?: T;
  isActive?: T;
  _lastEdited?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fiat-to-crypto_select".
 */
export interface FiatToCryptoSelect<T extends boolean = true> {
  amount?: T;
  currency?: T;
  userSendsDetail?: T;
  amountSentToExchangeOriginalRateDetail?: T;
  amountReceivedFromExchangeDetail?: T;
  rateDetail?: T;
  profitAmountDetail?: T;
  profitPercentageDetail?: T;
  userReceivesDetail?: T;
  sentToReference?: T;
  transaction?: T;
  status?: T;
  invoiceImage?: T;
  method?: T;
  referenceNumber?: T;
  senderAddress?: T;
  txHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crypto-to-fiat_select".
 */
export interface CryptoToFiatSelect<T extends boolean = true> {
  amount?: T;
  currency?: T;
  userSendsDetail?: T;
  amountSentToExchangeOriginalRateDetail?: T;
  amountReceivedFromExchangeDetail?: T;
  rateDetail?: T;
  profitAmountDetail?: T;
  profitPercentageDetail?: T;
  userReceivesDetail?: T;
  sentToReference?: T;
  transaction?: T;
  status?: T;
  method?: T;
  txHash?: T;
  receiverDetails?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}